#Hugo configuration
title = "qedsf"
baseURL = "https:\/\/dsvsd.xzcv.werf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
reservedContentFolders = "brands,popular,hello"
